config:
  batch_size: 128
  device: cuda
  epochs: 300
  lr: 0.001
  lr_gamma: 0.1
  lr_step_size: 50
  lr_steps:
  - 100
  - 150
  max_norm: 0
  model:
    control: false
    decay_lr: 0.95
    device: cuda
    extra_depth: true
    fast_lr: 0.5
    hidden_size: 128
    input_size: 37
    layer_norm: true
    out_size: 37
  momentum: 0.9
  output_dir: models/
  patience: 10
  reduce_type: min
  resume: 0
  scheduler: none
  weight_decay: 0.0005
  workers: 16
dir: exps/exp_0_1_1_1/
log_dir: logs/
name: exp_0_1_1_1
